const services = [
    {
        name: "Facebook",
        category: "social",
        rating: 11,
        popularity: 90,
        free: true,
        openSource: false,
        partiallyOpenSource: true,
        ads: true,
        inAppPurchases: true,
        endToEndEncrypted: false,
        fiveEyes: true,
        nineEyes: false,
        fourteenEyes: false,
        torAvailable: true,
        description: "US-based public company owned by Meta.",
        detailPage: "pages/services/facebook.html" // Path to its own page
    },
    {
        name: "X/Twitter",
        category: "social",
        rating: 11,
        popularity: 85,
        free: true,
        openSource: false,
        partiallyOpenSource: true,
        ads: true,
        inAppPurchases: true,
        endToEndEncrypted: false,
        fiveEyes: true,
        nineEyes: false,
        fourteenEyes: false,
        torAvailable: false,
        description: "Owned by X Corp, a private company based in the US.",
        detailPage: "pages/services/twitter.html" // Path to its own page
    },
    {
        name: "Discord",
        category: "social",
        rating: 9,
        popularity: 75,
        free: true,
        openSource: false,
        partiallyOpenSource: false,
        ads: true,
        inAppPurchases: true,
        endToEndEncrypted: false,
        fiveEyes: true,
        nineEyes: false,
        fourteenEyes: false,
        torAvailable: false,
        description: "Private, US-based company.",
        detailPage: "pages/services/discord.html" // Path to its own page
    }
];
